name: 'AppMicroserviceAction'
description: 'Deploy resources for microservice'
inputs:
  app-name:
    description: 'Application id'
    default: ''
  app-suffix:
    description: 'Suffix for namming'
    default: ''
  aws-role:
    description: 'Aws role to apply changes'
    default: ''
  terraform-version:
    description: 'Terraform version to install'
    default: '1.9.7'
  terragrunt-version:
    description: 'Terragrunt version to install'
    default: '0.68.1'
  application-repo:
    description: 'terraform-app-microservice repository'
    default: 'FinalCAD/terraform-app-microservice'
  application-ref:
    description: 'Ref to use for pulling repo terraform-app-microservice'
    default: 'master'
  github-token:
    description: 'Github token to pull package to avoid limit rate'
    default: ''
  github-ssh:
    description: 'Github ssh key to pull terragrunt from github api'
    default: ''
  environment:
    description: 'Finalcad envrionment: production, staging, sandbox'
    default: ''
  region-friendly:
    description: 'Finalcad region: frankfurt or tokyo'
    default: 'frankfurt'
  application-file:
    description: 'File with path for application configuration'
    default: '.finalcad/application.yaml'
  dry-run:
    description: 'Dry run'
    default: ''
runs:
  using: 'composite'
  steps:
    - name: Deprecated version of FinalCAD/AppDeployAction
      shell: bash
      run: |
        echo '::error title=Deprecated version of FinalCAD/AppMicroserviceAction::This version of FinalCAD/AppMicroserviceAction is deprecated use `v1` instead.'
        exit 1
